# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

# Description: This file contains the docker-compose configuration for the redis-sentinel module.  
services:
  redis:
    image: redis:7
    command: [
      "redis-server",
      "--appendonly", "yes",
      "--bind", "0.0.0.0",
      "--replica-announce-ip", "$${HOST_IP}",
      "--replica-announce-port", "${redis_port+1}",
      "--protected-mode", "no"%{if redis_password != null && redis_password != "" },
      "--requirepass", "${redis_password}",
      "--masterauth", "${redis_password}"
      %{endif}
    ]
    ports:
      - "${redis_port+1}:${redis_port}"
    healthcheck:
      test: [ "CMD", "redis-cli", "-h", "localhost", "ping" ]
      interval: 1s
      timeout: 5s
      retries: 5

  redis-follower-1:
    image: redis:7
    command: [
      "redis-server",
      "--replicaof", "redis", "${redis_port}", "-a", "'${redis_password}'",
      "--bind", "0.0.0.0",
      "--replica-announce-ip", "$${HOST_IP}",
      "--replica-announce-port", "${redis_port+2}",
      "--protected-mode", "no"%{if redis_password != null && redis_password != "" },
      "--requirepass", "${redis_password}",
      "--masterauth", "${redis_password}"
      %{endif}
    ]
    depends_on:
      redis:
        condition: service_healthy
    ports:
      - "${redis_port+2}:${redis_port}"
    healthcheck:
      test: [ "CMD", "redis-cli", "-h", "localhost", "-p", "${redis_port}", "-a", "'${redis_password}'", "ping" ]
      interval: 1s
      timeout: 5s
      retries: 5

  redis-follower-2:
    image: redis:7
    command: [
      "redis-server",
      "--replicaof", "redis", "${redis_port}", "-a", "'${redis_password}'",
      "--bind", "0.0.0.0",
      "--replica-announce-ip", "$${HOST_IP}",
      "--replica-announce-port", "${redis_port+3}",
      "--protected-mode", "no"%{if redis_password != null && redis_password != "" },
      "--requirepass", "${redis_password}",
      "--masterauth", "${redis_password}"
      %{endif}
    ]
    depends_on:
      redis:
        condition: service_healthy
    ports:
      - "${redis_port+3}:${redis_port}"
    healthcheck:
      test: [ "CMD", "redis-cli", "-h", "localhost", "-p", "${redis_port}", "-a", "'${redis_password}'", "ping" ]
      interval: 1s
      timeout: 5s
      retries: 5

  sentinel-1:
    image: redis:7
    depends_on:
      redis:
        condition: service_healthy
      redis-follower-1:
        condition: service_healthy
      redis-follower-2:
        condition: service_healthy
    ports:
      - "${redis_sentinel_port}:${redis_sentinel_port}"
    volumes:
      - $${SENTINEL_ENTRYPOINT}:/usr/local/bin/entrypoint.sh
    entrypoint: [ "/usr/local/bin/entrypoint.sh" ]
    environment:
      - HOST_IP=$${HOST_IP}
    healthcheck:
      test: [ "CMD", "redis-cli", "-h", "localhost", "-p", "${redis_sentinel_port}", "ping" ]
      interval: 5s
      timeout: 10s
      retries: 5

  sentinel-2:
    image: redis:7
    depends_on:
      redis:
        condition: service_healthy
      redis-follower-1:
        condition: service_healthy
      redis-follower-2:
        condition: service_healthy
    ports:
      - "${redis_sentinel_port+1}:${redis_sentinel_port}"
    volumes:
      - $${SENTINEL_ENTRYPOINT}:/usr/local/bin/entrypoint.sh
    entrypoint: [ "/usr/local/bin/entrypoint.sh" ]
    environment:
      - HOST_IP=$${HOST_IP}
    healthcheck:
      test: [ "CMD", "redis-cli", "-h", "localhost", "-p", "${redis_sentinel_port}", "ping" ]
      interval: 5s
      timeout: 10s
      retries: 5
