# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

# Description: This file contains the docker-compose configuration for the redis OSS module.  
services:
  redis:
    image: redis:7
    entrypoint: ["/opt/redis/init.sh"]
    command: [
      "redis-server",
      # disable all ports
      "--port", "0",
      "--tls-port 6379",
      "--tls-cert-file", "/certs/fullchain.pem",
      "--tls-key-file", "/certs/privkey.pem",
      "--tls-ca-cert-file", "/certs/isrgrootx1.pem",
      "--tls-auth-clients", "yes"
    ]
    ports:
      - "${redis_port+1}:${redis_port}"
    volumes:
      # For Redis TLS certificates.
      - $${FULLCHAIN}:/certs/fullchain.pem
      - $${PRIVKEY}:/certs/privkey.pem
      - $${ISRGROOTX1}:/certs/isrgrootx1.pem




